#+title: EDG Highlights for NPPS

This page attempts to collect highlights of software-related activity
by EDG members that may be interesting to NPPS.  Below are weekly
summaries.  Less frequently updated but more focused updates on
Wire-Cell can be found in the [[https://wirecell.github.io/news/][Wire-Cell News blog]].

* Weekly highlights

** [2019-12-06 Fri]

- BV and Haiwang met with CSI (Meifeng, Kwangmin, Zhihua) yesterday to
  sync up about recent HEP-CCE activities as well as Wire-Cell
  parallelizing/optimizing.  BV was asked to participate in CCE-IOS
  (I/O + storage, meeting next Friday), Meifeng is in CCE-PPS
  (portable parallelism, meeting next Monday) and asked BV to
  participate in that as well.  

  Haiwang reported on his recent work on Wire-Cell's component-level
  parallel execution engine based on TBB.  Single threaded jobs are
  just above 1 GB, multi-threaded jobs with 1 pipeline for each of 6
  ProtoDUNE APAs achieves near 600% CPU usage in those pipelines and
  uses less than 3 GB.  

  Haiwang also presented his work on improvements on the quality of
  the "region-of-interest" half of Wire-Cell signal processing via
  machine learning techniques based on image segmentation.  Evaluation
  is based on visually checking ROI results and is clearly better than
  the current heuristic based ROI finding in terms of completeness and
  spatial resolution.  Kwangmin remarked on the relatively low number
  of training epochs used (5) and Haiwang will investigate how results
  might change as a function of this number.

- A new project ([[https://github.com/brettviren/zio][zio]]) was started as a basis for solutions of several
  similar problems but in rather different spaces.  Some additional
  info is in the README and updates will be provided as the project
  develops.

- The [[https://github.com/brettviren/tpquery][TP Query]] package for DUNE FD DAQ reached an initial milestone of
  usability.  It provides a ZeroMQ based streamed buffer query system
  based on interval trees and applied to providing a database of
  recent self-trigger information for ProtoDUNE.  It was tested using
  PTMP's "replay" mechanism with trigger messages dumped from
  ProtoDUNE.  It sustains sufficient throughput for buffers of a few
  seconds deep for the aggregate of 1 APA (~80kHz of intervals) but
  will slow beyond that (the relevant interval tree operations are
  N*log(N)).  This is likely sufficient as-is but at least one
  approach exists to combat this slowdown if longer buffers are
  needed.  It's unclear when this might be tested "live" at ProtoDUNE
  but it was recently learned that PDSP will run into April.
  Unidentified artdaq developer effort is needed if this buffer query
  is to lead to data sent to offline files but a quicker "live" test
  can be developed entirely using PTMP based code.

** [2019-11-22 Fri]

- DUNE computing issued a charge for a "DUNE Software Framework
  Requirements Task Force":

  https://indico.fnal.gov/event/22493/contribution/9/material/slides/3.pdf

  to be led by Paul Laycock and Andrew Norman (of FNAL).

- Report on Wire-Cell Toolkit to LArSoft Coordination meeting by
  Haiwang Yu

  https://indico.fnal.gov/event/22501/contribution/1/material/slides/0.pdf

  Good overview of WCT's data flow programming paradigm, some of the
  algorithms, initial look at ROOT vs HDF5, single/multi-threading
  comparisong, memory usage, identified lock bottleneck in FFTW3.

- DUNE FD DAQ began technical discussions about how to handle
  "observability" with initial focus on metrics.  Two presentations
  are here https://indico.fnal.gov/event/22481/.  Of particular note
  to NPPS, I mentioned Sergey Padolski's BDT work for Panda as
  something we should look into more.

** [2019-11-15 Fri]

- [[https://indico.bnl.gov/event/6383/contributions/32818/attachments/25515/38251/srv-dune-fd-daq-bv.pdf][DUNE DAQ at SRV]] describes the prototype streaming trigger/readout software and some results of [[https://github.com/brettviren/zperfmq][ZeroMQ performance]] on 100 Gbps ATLAS/DUNE/sPHENIX LDRD test network.

- [[https://www.bnl.gov/dmo2019/][Module of oprotunity]] workshop at BNL discussed what DUNE might put in as the fourth of four far detector modules.  Mostly physics and detector related.   [[https://indico.fnal.gov/event/21535/contribution/22/material/slides/0.pptx][Xin Qian's talk]] shows many Wire-Cell results and includes some new ideas on LArTPC signal processing including early promising results using deep learning by our post-doc Haiwang Yu.

- Couple of notes posted
  - [[http://docs.dunescience.org/cgi-bin/ShowDocument?docid=16973][DUNE DocDB 16973]] some unfinished notes on "observability" systems of possible interest for DUNE FD DAQ.
  - [[http://docs.dunescience.org/cgi-bin/ShowDocument?docid=16976][DUNE DocDB 16976]] write up of performance evaluation of ZeroMQ on 100 Gbps using ZperfMQ.

